#ifndef GPUFILTERCORE_GLOBAL_H
#define GPUFILTERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GPUFILTERCORE_LIBRARY)
#  define GPUFILTERCORE_EXPORT Q_DECL_EXPORT
#else
#  define GPUFILTERCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // GPUFILTERCORE_GLOBAL_H
