#ifndef GPUFILTERGENERALSCENE_GLOBAL_H
#define GPUFILTERGENERALSCENE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GPUFILTERGENERALSCENE_LIBRARY)
#  define GPUFILTERGENERALSCENE_EXPORT Q_DECL_EXPORT
#else
#  define GPUFILTERGENERALSCENE_EXPORT Q_DECL_IMPORT
#endif

#endif // GPUFILTERGENERALSCENE_GLOBAL_H
