#ifndef GPUFILTERFRAMECONVERT_GLOBAL_H
#define GPUFILTERFRAMECONVERT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GPUFILTERFRAMECONVERT_LIBRARY)
#  define GPUFILTERFRAMECONVERT_EXPORT Q_DECL_EXPORT
#else
#  define GPUFILTERFRAMECONVERT_EXPORT Q_DECL_IMPORT
#endif

#endif // GPUFILTERFRAMECONVERT_GLOBAL_H
