#ifndef GPUFILTERMODEL_GLOBAL_H
#define GPUFILTERMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GPUFILTERMODEL_LIBRARY)
#  define GPUFILTERMODEL_EXPORT Q_DECL_EXPORT
#else
#  define GPUFILTERMODEL_EXPORT Q_DECL_IMPORT
#endif

#endif // GPUFILTERMODEL_GLOBAL_H
